---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
  labels:
    app: hello-world
spec:
  selector:
   app: hello-world
  type: NodePort
  ports:
  - nodePort: 30163
    name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: test-task
        name: hello-world
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
        ports:
          - containerPort: 8080
            name: http
        imagePullPolicy: Never